version: '3.7'

services:
  metrics_exporter:
    build: exporter
    image: floki/metrics-exporter

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
      - 443:443
    depends_on:
      - metrics_exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards

volumes:
  grafana-storage:
    external: true
