global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'floki-metrics'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['metrics_exporter:9999']

# remote_write:

#   - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push

#     basic_auth:
#       username: <username>
#       password: <password>
