{
 "title": "Floki Inu",
 "description": "Floki Inu metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Market Cap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "floki_market_cap" }
   ]
  },
  {
   "title": "Current Total Circulating",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"totalCirculating\"}",
     "legendFormat": "Total Circulating"
    }
   ]
  },
  {
   "title": "Current Total Burn Per Hour",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(floki_metrics{metric_types=\"bscBurned\"}[1h]) + ignoring(metric_types) delta(floki_metrics{metric_types=\"ethBurned\"}[1h])"
    }
   ]
  },
  {
   "title": "Total Burn Per Hour ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(floki_metrics{metric_types=\"bscBurned\"}[1h]) + ignoring(metric_types) delta(floki_metrics{metric_types=\"ethBurned\"}[1h])",
     "legendFormat": "Tokens Burned Per Hour"
    }
   ]
  },
  {
   "title": "Combined Market Cap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "floki_market_cap", "legendFormat": "Combined Market Cap" }
   ]
  },
  {
   "title": "Total circulating",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"totalCirculating\"}",
     "legendFormat": "Total circulating"
    }
   ]
  },
  { "title": "BSC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "BSC Burned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"bscBurned\"}",
     "legendFormat": "BSC Burned"
    },
    {}
   ]
  },
  {
   "title": "BSC LP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"bscLp\"}",
     "legendFormat": "BSC LP"
    }
   ]
  },
  {
   "title": "BSC Bridge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"bscBridge\"}",
     "legendFormat": "BSC Bridge"
    }
   ]
  },
  {
   "title": "BSC Circulating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"bscCirculating\"}",
     "legendFormat": "BSC Circulating"
    }
   ]
  },
  { "title": "ETH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "ETH Burned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"ethBurned\"}",
     "legendFormat": "ETH Burned"
    }
   ]
  },
  {
   "title": "ETH LP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"ethLp\"}",
     "legendFormat": "ETH LP"
    }
   ]
  },
  {
   "title": "ETH Bridge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"ethBridge\"}",
     "legendFormat": "ETH Bridge"
    }
   ]
  },
  {
   "title": "ETH Circulating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floki_metrics{metric_types=\"ethCirculating\"}",
     "legendFormat": "ETH Circulating"
    }
   ]
  }
 ]
}